\input texinfo @c SPDX-License-Identifier: GPL-3.0-or-later
@documentencoding UTF-8

@include config.texi

@settitle GDIoT Documentation

@copying
GDIoT Copyright @copyright{} @value{COPYYEAR} @value{AUTHOR}

@quotation
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
@end quotation
@end copying

@titlepage
@title Generalized Deduplication for IoT
@author @value{AUTHOR}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top GDIoT

Chapters in the @acronym{GDIoT} documentation.
@end ifnottex

@menu
* GDIoT Copying Conditions:: What you are allowed to do with this software
* Introduction:: The idea behind @acronym{GDIoT}
* Build System:: Description of the build systems and how to used it
* Program:: Programs that come with @acronym{GDIoT}
* Index:: An index of concepts
* Program Index:: An index of all involved programs
@end menu

@node GDIoT Copying Conditions
@unnumbered GDIoT Copying Conditions

GDIoT: Generalized Deduplication for the Internet of Things
Copyright @copyright{} @value{COPYYEAR}  @value{AUTHOR}

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see @url{https://www.gnu.org/licenses/}.

@node Introduction
@chapter Introduction

@cindex chapter, Introduction

@acronym{GDIoT,Generalized Deduplication for @acronym{IoT,Internet of Things}} is a open-source software project that enables generalized deduplication for @acronym{IoT} through the Hermes protocol.

@node Build System
@chapter Build System

@cindex chapter, Build System

The build system is inspired by @emph{ffbuild}.
@pindex configure
Due to time constraints during the development of the @acronym{GDIoT} project, it lacks a @file{configure} script.
Instead it provides a configuration template @file{config.tmpmk} that needs to be modified by hand before compiling the project.
@pindex make
After modifying the configuration template save it as @file{config.mk} in @acronym{GDIoT}'s root directory and run @command{make}.

@example
cp config.tmph config.h
$EDITOR config.h
cp config.tmpmk config.mk
$EDITOR config.mk
cp doc/config.tpmi doc/config.texi
$EDITOR doc/config.texi
make
@end example

@node Program
@chapter Program

@cindex chapter, Program

@acronym{GDIoT} provides a reference implementation for a source node.

@menu
* gdiot-src:: source node
* gdiot-gate:: intermediate node
* gdiot-evap:: sink node
@end menu

@node gdiot-src
@section gdiot-src

@cindex section, gdiot-src
@pindex gdiot-src

@command{gdiot-src} is a reference implementation for a source node.

@node gdiot-gate
@section gdiot-gate

@cindex section, gdiot-gate
@pindex gdiot-gate

@command{gdiot-gate} is a reference implementation for an intermediate node.

@node gdiot-evap
@section gdiot-evap

@cindex section, gdiot-evap
@pindex gdiot-evap

@command{gdiot-evap} is a reference implementation for a sink node.

@node Index
@unnumbered Index

@printindex cp

@node Program Index
@unnumbered Program Index

@printindex pg

@bye
